NUT_SERVERS:
  - HOST: __NUT_HOST__
    PORT: __NUT_PORT__
    USERNAME: __NUT_USERNAME__
    PASSWORD: __NUT_PASSWORD__
INFLUX_HOST: ''
INFLUX_TOKEN: ''
INFLUX_ORG: ''
INFLUX_BUCKET: ''
INFLUX_INTERVAL: 10
