#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

auth_secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=auth_secret --value=$auth_secret

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

    ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

    ynh_config_add --template=".env" --destination="$install_dir/.next/standalone/config/.env"

#=================================================
# INSTALL AND BUILD THE APP
#=================================================

pushd $install_dir
npm install --global corepack@latest
corepack enable pnpm
ynh_exec_as_app corepack use pnpm@10.25.0
ynh_script_progression "Installing the $app..."
    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" pnpm install --frozen-lockfile

ynh_script_progression "Building the $app..."
    ynh_hide_warnings ynh_exec_as_app NODE_PTIONS="--max-old-space-size=4096" pnpm run build:local
    ynh_config_add --template="settings.yml" --destination="$install_dir/.next/standalon/config/settings.yml"
    hash_password=$(bcrypt "$password")
    ynh_config_add --template="auth.yaml" --destination="$install_dir/.next/standalon/config/auth.yml"
popd 

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

    ynh_config_add_systemd
    yunohost service add $app --description="PeaNUT Dashboard" --log="/var/log/$app/$app.log"
    ynh_config_add_logrotate
    
    ynh_config_add_nginx

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

    ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
